### PR TITLE
Fix #3961 - Fix build error with Python bindings due to zlib's crypt.h

### LINKED ISSUE #3961: Failed to build Python bindings on Ubuntu with 3.x
Issue overview
--------------

reported on #3940 by @damianCaceres

## Current Behavior

When building the python bindings `-DBUILD_PYTHON_BINDINGS=ON`, user hit a build error.

```
damian@damian-HP:~$ conan --version
Conan version 1.24.1
```

```
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0/build/src/radiance/python_OpenStudioRadiance_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/build.make:1374: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o' failed
make[2]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:3627: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all' failed
make[1]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....


In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0/build/src/gbxml/python_OpenStudioGBXML_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/build.make:1373: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o' failed
make[2]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:3775: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all' failed
make[1]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all] Error 2


```

User reported trying to change
https://github.com/NREL/OpenStudio/blob/17912d4d6be39e999fdd174908189b8a61b2ada5/ConanInstall.cmake#L75

to `zlib/1.2.11@conan/stable`: 

> Yes. I've changed the line 75 in the file ConanInstall.cmake
I know because OpenStudio SDK v3.0.0-pre1 works fine
Thank you very much

>I can compile with zlib/1.2.11@conan/stable, but the bindings have problems when they are imported. Now I'm starting to test them.
I'll come back to OpenStudio 2.9.1, which works very well. NO URGENT
Thank you

> After compile OpenStudio 3.0.0 I have got
> ```
> /usr/local/OpenStudio-3.0.0/Python/_openstudiomodel.so: undefined symbol: _ZTIN10openstudio9WorkspaceE
> ```
> I imagine that is due to swig 4 ... (wrong comment)

## Expected Behavior

It should work to build the Python bindings

## Steps to Reproduce

Use Ubuntu 18.04, build with  `-DBUILD_PYTHON_BINDINGS=ON`

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 18.04
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.0, 17912d4d6be39e999fdd174908189b8a61b2ada5

### Context

Trying to build the Python Bindings

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3961
 - Update the cmake call to find python to modern cmake's `FindPython` instead of FindPythonInterp, and default to using py3 if not specified since python 2 has been EOL since January 1, 2020.
- Use my own fork of zlib/1.2.11@nrel/testing where I made it not install the minizip `crypt.h`

Build of python bindings now suceeds, so fix #3961. The python bindings are still broken, but that should be addressed separately.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: ConanInstall.cmake [hunk 1]
```diff
@@ -72,7 +72,7 @@ if(NOT CONAN_OPENSTUDIO_ALREADY_RUN)
     #boost_geometry/${BOOST_VERSION}@bincrafters/stable
     pugixml/1.10@bincrafters/stable
     jsoncpp/1.9.2
-    zlib/1.2.11
+    zlib/1.2.11@nrel/testing # TODO: Temp, pending merging of https://github.com/conan-io/conan-center-index/pull/1526, to resolve #3961
```
Comment (tijcolem) [inline ConanInstall.cmake:75]: Looks like this has been approved and just wanting on the merge.  https://github.com/conan-io/conan-center-index/pull/1526.  It'd be nice to have a ref to the official vs using the NREL so we can wait on this for another couple of days and check back.

Comment (jmarrec) [reply ConanInstall.cmake:75]: It won't be merged until I get approved in their Early access program, where access is granted by batches every two or three weeks from what I gathered after asking them directly. 

It also ties into #3940, at some point I'd just make this nrel/stable instead of nrel/testing and that's it.

Comment (tijcolem) [reply ConanInstall.cmake:75]: okay, well if that's the case we can make the change at later date.
