### ISSUE TITLE
Develop3 measure failure

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio#3614]
an osw that works in 2.8.1 is not working in develop3-2.8.1.

getting undefined method `getSolarAbsorptance' for #<OpenStudio::Model::StandardOpaqueMaterial:0x000055774b897bd8>, which should work.
[develop3-error.txt](https://github.com/NREL/OpenStudio/files/3472957/develop3-error.txt)
[develop3_error.zip](https://github.com/NREL/OpenStudio/files/3472958/develop3_error.zip)

cli commands and error messages attached along with files to replicate

**Comment by macumber** [comment]
That method returns a quantity object it was deprecated in develop3, the measure should be updated to not use that method

**Comment by macumber** [comment]
Can use solarAbsorptance instead

https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/model/MasslessOpaqueMaterial.hpp#L82

**Comment by brianlball** [comment]
yep, that plus a few other deprecated methods fixed it.
