### PR TITLE
Fix #5546 - Adjust overrride of Dir.glob so that it finds json_schema attributes

### LINKED ISSUE #5546: `json-schema` gem is broken
### Description

Trying to validate a JSON object against a schema throws an error in recent versions of OpenStudio. Since the gem keeps breaking (see [here](https://github.com/NREL/OpenStudio/issues/4870) and [here](https://github.com/NREL/OpenStudio/issues/5208)), it'd be nice if OpenStudio could add a unit test around this.

### Current Behavior

Here's what I get in OpenStudio 3.9, 3.10, and 3.11-rc1:

```
openstudio -e 'require "stringio"; require "json-schema"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'

terminate called after throwing an instance of 'RubyException'
  what():  NoMethodError: undefined method `validate' for nil:NilClass
Aborted (core dumped)
```

### Expected Behavior

It worked in OpenStudio 3.8:

```
openstudio -e 'require "stringio"; require "json-schema"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'

The property '#/a' of type String did not match the following type: integer
```

### Steps to reproduce

See above.

### Possible Solution

_No response_

### Operating System affected

_No response_

### Environment

Ubuntu 24.04

### Version of OpenStudio

3.11.0-rc1+dee62bf9dd

### Context

_No response_

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5546

## Demonstration

```
git@github.com:voxpupuli/json-schema.git
cd json-schema/lib
gvim test.rb
```

**test.rb**

```ruby
files = [
  "json-schema/attributes/format.rb",
  "json-schema/attributes/formats/custom.rb"
]

match_all_patterns = [
  "json-schema/**/*.rb",
  "json-schema/attributes/**/*.rb",
]

match_only_single_patterns = [
  "json-schema/attributes/*.rb",
  "json-schema/attributes/*/*.rb",
]

puts "|             Pattern            |                   File                   | Matches  | Matches (FNM_PATHNAME) | Expected |"
puts "|--------------------------------|------------------------------------------|----------|------------------------|----------|"
match_all_patterns.each do |pattern|
  files.each do |f|
    matches = File.fnmatch(pattern, f)
    matches_pathname = File.fnmatch(pattern, f, File::FNM_PATHNAME)
    expected = Dir.glob(pattern).include?(f)
    puts "| #{pattern.ljust(30)} | #{f.ljust(40)} | #{matches.to_s.center(8)} | #{matches_pathname.to_s.center(22)} | #{expected.to_s.center(8)} |"
  end
end

match_only_single_patterns.each do |pattern|
  files.each do |f|
    matches = File.fnmatch(pattern, f)
    matches_pathname = File.fnmatch(pattern, f, File::FNM_PATHNAME)
    expected = Dir.glob(pattern).include?(f)
    puts "| #{pattern.ljust(30)} | #{f.ljust(40)} | #{matches.to_s.center(8)} | #{matches_pathname.to_s.center(22)} | #{expected.to_s.center(8)} |"
  end
end
```

```
$ruby test.rb
|             Pattern            |                   File                   | Matches  | Matches (FNM_PATHNAME) | Expected |
|--------------------------------|------------------------------------------|----------|------------------------|----------|
| json-schema/**/*.rb            | json-schema/attributes/format.rb         |   true   |          true          |   true   |
| json-schema/**/*.rb            | json-schema/attributes/formats/custom.rb |   true   |          true          |   true   |
| json-schema/attributes/**/*.rb | json-schema/attributes/format.rb         |  false   |          true          |   true   |
| json-schema/attributes/**/*.rb | json-schema/attributes/formats/custom.rb |   true   |          true          |   true   |
| json-schema/attributes/*.rb    | json-schema/attributes/format.rb         |   true   |          true          |   true   |
| json-schema/attributes/*.rb    | json-schema/attributes/formats/custom.rb |   true   |         false          |  false   |
| json-schema/attributes/*/*.rb  | json-schema/attributes/format.rb         |  false   |         false          |  false   |
| json-schema/attributes/*/*.rb  | json-schema/attributes/formats/custom.rb |   true   |          true          |   true   |
```

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: ruby/engine/embedded_help.rb [hunk 1]
```diff
@@ -667,6 +667,8 @@ def self.glob(pattern, _flags = 0, flags: _flags, base: nil, sort: true)
     override_args_extglob = true
 
     flags = flags | File::FNM_EXTGLOB if override_args_extglob
+    # Without this 'path/**/*.rb' will match 'path/sub/file.rb' but not 'path/file.rb', cf #5546
+    flags = flags | File::FNM_PATHNAME
```
Comment (jmarrec) [inline ruby/engine/embedded_help.rb:671]: Can't be fooled by the amount of code change, massive pain to diagnose and fix.

`<broken record>`We should drop the embedded shenanigans!`</broken record>`

File: src/cli/test/test_embedded_ruby.rb [hunk 2]
```diff
@@ -242,4 +242,30 @@ def test_json_schemer
...
+
+    data_invalid = { "a" => "taco" }
+
+    error = assert_raises(JSON::Schema::ValidationError) do
+      # "The property '#/a' of type String did not match the following type: integer"
+      JSON::Validator.validate!(schema, data_invalid)
+    end
+    assert_match(/The property '#\/a' of type string did not match the following type: integer/, error.message)
+
+  end
```
Comment (jmarrec) [inline src/cli/test/test_embedded_ruby.rb:269]: As @shorowit pointed out, a test is an excellent idea...

Before fix

```
  1) Error:
EmbeddedRuby_Test#test_json_schema:
NoMethodError: undefined method `validate' for nil:NilClass
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/schema/validator.rb:25:in `block in validate'
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/schema/validator.rb:23:in `each'
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/schema/validator.rb:23:in `validate'
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/schema.rb:32:in `validate'
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/validator.rb:115:in `validate'
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/validator.rb:259:in `validate!'
    :/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/validator.rb:243:in `validate'
    /home/julien/Software/Others/OpenStudio/src/cli/test/test_embedded_ruby.rb:259:in `test_json_schema'
```
