### PR TITLE
Fix #4931 - Install C# OpenStudio.dll properly.

### LINKED ISSUE #4931: Why is OpenStudio.dll no longer included in the installers?
Enhancement Request
--------------
I'm opening this as an enhancement request but it may be more of a question and I just have not found the right answer yet. Starting from OpenStudio 3.5, it seems that there is no longer an `OpenStudio.dll` included in the Windows exe installer and the only way that I have currently found to obtain this .dll is from the OpenStudio [NuGet package](https://www.nuget.org/packages/OpenStudio).

This seemed odd to me because all of the other csharp dlls are in the installer but I am missing the critical one that I need in order to be able to make use of the CSharp bindings.
image

So I first wanted to ask if this is the intended setup and I am just not understanding how I am now supposed to be making use of the CSharp bindings (eg. should I be adding a different one of these dlls?) If it is the intended setup, could you instruct me on which dll should be added to enable me to import OpenStudio SDK in .NET. Or do I need to add all of them?

If this is not the intended setup, it would be really nice if future OpenStudio installers could put back the `OpenStudio.dll` somewhere in the installation folder. I have verified that the latest OpenStudio 3.6.1 installer also lacks the `OpenStudio.dll`

Thanks, as always.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4931

**Let's see if CI makes an installer with the OpenStudio.dll**

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: csharp/CMakeLists.txt [hunk 1]
```diff
@@ -60,14 +61,11 @@ target_compile_options(csharp_warnings INTERFACE "$<${is_gnu_or_clang_genex}:-Wn
 # custom command to make OPENSTUDIO_CSHARP_DLL
 add_custom_command(
   OUTPUT ${OPENSTUDIO_CSHARP_DLL}
-  COMMAND "${DOTNET}" "build" "-c" "$<CONFIGURATION>" "/p:Platform=${CSHARP_PLATFORM}" "${PROJECT_BINARY_DIR}/csharp_wrapper/OpenStudio.csproj"
+  COMMAND "${DOTNET}" "build" "-c" "$<CONFIG>" "/p:Platform=${CSHARP_PLATFORM}" "${PROJECT_BINARY_DIR}/csharp_wrapper/OpenStudio.csproj"
```
Comment (jmarrec) [inline csharp/CMakeLists.txt:64]: CONFIGURATION genex is deprecated since cmake 3.0 and replaced with CONFIG

File: csharp/CMakeLists.txt [hunk 2]
```diff
@@ -60,14 +61,11 @@ target_compile_options(csharp_warnings INTERFACE "$<${is_gnu_or_clang_genex}:-Wn
...
   DEPENDS ${ALL_CSHARP_WRAPPER_TARGETS} ${ALL_CSHARP_WRAPPER_FILES}
 )
 
-
-install(FILES "${OPENSTUDIO_CSHARP_DLL}" DESTINATION CSharp/openstudio/ CONFIGURATIONS DEBUG COMPONENT "CSharpAPI")
-
-
+install(FILES "${OPENSTUDIO_CSHARP_DLL}" DESTINATION CSharp/openstudio/ COMPONENT "CSharpAPI")
```
Comment (jmarrec) [inline csharp/CMakeLists.txt:68]: Install it regardless of the configuration. It was done only for DEBUG prior

File: csharp/CMakeLists.txt [hunk 3]
```diff
@@ -48,7 +48,8 @@ endif()
 
 # The Release/Debug can be stripped probably
 # Also probably don't need to use multiple `<TargetFrameworks>` which is the reason there's an extra netstandard2.0/ level
-set(OPENSTUDIO_CSHARP_DLL "${CSHARP_LIBRARY_OUTPUT_DIRECTORY}/${CMAKE_BUILD_TYPE}/netstandard2.0/OpenStudio.dll")
+# Note: can't use CMAKE_BUILD_TYPE as it's empty for multi generators (MSVC for eg). So we use a genex
+set(OPENSTUDIO_CSHARP_DLL "${CSHARP_LIBRARY_OUTPUT_DIRECTORY}/$<CONFIG>/netstandard2.0/OpenStudio.dll")
```
Comment (jmarrec) [inline csharp/CMakeLists.txt:52]: See the note.

Comment (jmarrec) [reply csharp/CMakeLists.txt:52]: I replaced the CMAKE_BUILD_TYPE with a genex too. This was working on CI because we do pass explicitly `cmake -DCMAKE_BUILD_TYPE:STRING=Release` when building on MSVC. But MSVC by default is **Multi-configuration** and CMAKE_BUILD_TYPE is empty if used like this.

File: CMakeLists.txt [hunk 4]
```diff
@@ -1216,7 +1216,9 @@ if(NOT UNIX)
   if(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
     install(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION "bin")
     install(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION "Ruby" COMPONENT "RubyAPI")
-    install(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION "CSharp/openstudio/" COMPONENT "CSharpAPI")
+    if (BUILD_CSHARP_BINDINGS)
+      install(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION "CSharp/openstudio/" COMPONENT "CSharpAPI")
+    endif()
```
Comment (jmarrec) [inline CMakeLists.txt:1221]: Don't install the runtimes libs there if C# isn't selected to begin with.

This threw me off when I was looking at the CI-built packages, because actually the incremental runner does not build C#!

File: ProjectMacros.cmake [hunk 5]
```diff
@@ -326,20 +326,8 @@ macro(MAKE_SWIG_TARGET NAME SIMPLENAME KEY_I_FILE I_FILES PARENT_TARGET PARENT_S
...
-      else()
-        message(STATUS "${MODULE_NAME} - Building SWIG Bindings for Python 2")
-      endif()
-    else()
-      # Python2 has been EOL since January 1, 2020
-      set(SWIG_PYTHON_3_FLAGS "-py3;-relativeimport")
-      message(STATUS "${MODULE_NAME} - Couldn't determine version of Python - Building SWIG Bindings for Python 3")
-    endif()
+    # The -py3 flag is now deprecated as Python 3 is the default the version used is Python 3
+    set(SWIG_PYTHON_3_FLAGS "-relativeimport")
```
Comment (jmarrec) [inline ProjectMacros.cmake:330]: Unrelated cleanup: Avoid having multiple warnings from swig saying "-py3 flag is deprecated"

File: src/utilities/core/CommonInclude.i [hunk 6]
```diff
@@ -66,7 +66,7 @@
 // and nested classes and "nothing known about <type>"
 // also ignoring #509, shadowed method. Its a red herring for all of our cases
 //#pragma SWIG nowarn=401,362,365,366,368,378,503,801,312
-#pragma SWIG nowarn=362,365,366,368,378,503,801,312,509,401
+#pragma SWIG nowarn=362,365,366,368,378,503,801,312,509,401,516
```
Comment (jmarrec) [inline src/utilities/core/CommonInclude.i:69]: Avoid thousands of "overloaded method ignore, using XXX instead". In particular for every modelObject, the Ctor is overloaded (rule of 5/6) so it was getting out of control.

File: python/SetupPython.cmake [hunk 7]
```diff
@@ -9,7 +9,7 @@ set(Python_USE_STATIC_LIBS OFF)
 if (PYTHON_VERSION)
   find_package(Python ${PYTHON_VERSION} EXACT REQUIRED COMPONENTS Interpreter Development OPTIONAL_COMPONENTS NumPy)
 else()
-  find_package(Python REQUIRED COMPONENTS Interpreter Development OPTIONAL_COMPONENTS NumPy)
+  find_package(Python 3 EXACT REQUIRED COMPONENTS Interpreter Development OPTIONAL_COMPONENTS NumPy)
```
Comment (jmarrec) [inline python/SetupPython.cmake:12]: Force finding python3, not python2, related to SWIG using py3 now. Python 2 is EOL since 2020 anyways, we do not want to support it.

File: ProjectMacros.cmake [hunk 8]
```diff
@@ -511,7 +499,7 @@ macro(MAKE_SWIG_TARGET NAME SIMPLENAME KEY_I_FILE I_FILES PARENT_TARGET PARENT_S
       # This is not working: "cannot open file 'python37.lib'"
       target_link_libraries(${swig_target} PUBLIC  ${${PARENT_TARGET}_depends})
       if (MSVC)
-        message("Python_LIBRARIES=${Python_LIBRARIES}")
+        message(DEBUG "Python_LIBRARIES=${Python_LIBRARIES}")
```
Comment (jmarrec) [inline ProjectMacros.cmake:502]: Shush this message too

File: src/utilities/core/jsoncpp.i [hunk 9]
```diff
@@ -2,7 +2,9 @@
 #define JSONCPP_I
 
 #if defined SWIGCSHARP
-%ignore openstudio::*::toJSON() const;
+  // ignores toJSON/fromJSON globally
+  %rename("$ignore", regextarget=1, fullname=1) "openstudio::.*::toJSON$";
+  %rename("$ignore", regextarget=1, fullname=1) "openstudio::.*::fromJSON$";
```
Comment (jmarrec) [inline src/utilities/core/jsoncpp.i:7]: If SWIGCSHARP, ignore toJSON and fromJSON globally.

File: src/utilities/filetypes/Filetypes.i [hunk 10]
```diff
@@ -18,9 +18,12 @@
   %ignore openstudio::WorkflowStepValue::WorkflowStepValue(std::string const&, char const*);
   %ignore openstudio::MeasureStep::setArgument(std::string const&, char const*);
 
-  // Ignore Json::Value return type
+  // Ignore Json::Value return type (toJSON / fromJSON are globally ignored already)
   %ignore openstudio::StandardsJSON::getPrimaryKey;
 
+  %ignore openstudio::CustomOutputAdapter::CustomOutputAdapter;
+  %ignore openstudio::CustomOutputAdapter::optionsJSON;
```
Comment (jmarrec) [inline src/utilities/filetypes/Filetypes.i:25]: Ignore other Json::Value related things in Filetypes.i when C#

Comment (jmarrec) [reply src/utilities/filetypes/Filetypes.i:25]: This will unbrick the develop build, which fails due to this problem currently, after the merge of #4917 (which we didn't realize it was going to break the build because the CI incremental windows runner does not build c# bindings...), cf https://ci.openstudio.net/blue/organizations/jenkins/openstudio-develop-full/detail/openstudio-develop-full/360/pipeline/98#step-101-log-921

```
D:\OSN\build\csharp_wrapper\generated_sources\OpenStudioUtilitiesData\SWIGTYPE_p_Json__Value.cs(13,14): 
error CS0101: The namespace 'OpenStudio' already contains a definition for 'SWIGTYPE_p_Json__Value' [D:\OSN\build\csharp_wrapper\OpenStudio.csproj]

D:\OSN\build\csharp_wrapper\generated_sources\OpenStudioUtilitiesFileTypes\SWIGTYPE_p_Json__Value.cs(13,14): 
error CS0101: The namespace 'OpenStudio' already contains a definition for 'SWIGTYPE_p_Json__Value' [D:\OSN\build\csharp_wrapper\OpenStudio.csproj]

D:\OSN\build\csharp_wrapper\generated_sources\OpenStudioUtilitiesData\SWIGTYPE_p_Json__Value.cs(16,12): error CS0111: Type 'SWIGTYPE_p_Json__Value' already defines a member called 'SWIGTYPE_p_Json__Value' with the same parameter types [D:\OSN\build\csharp_wrapper\OpenStudio.csproj]

D:\OSN\build\csharp_wrapper\generated_sources\OpenStudioUtilitiesData\SWIGTYPE_p_Json__Value.cs(20,13): error CS0111: Type 'SWIGTYPE_p_Json__Value' already defines a member called 'SWIGTYPE_p_Json__Value' with the same parameter types [D:\OSN\build\csharp_wrapper\OpenStudio.csproj]

D:\OSN\build\csharp_wrapper\generated_sources\OpenStudioUtilitiesFileTypes\SWIGTYPE_p_Json__Value.cs(16,12): error CS0111: Type 'SWIGTYPE_p_Json__Value' already defines a member called 'SWIGTYPE_p_Json__Value' with the same parameter types [D:\OSN\build\csharp_wrapper\OpenStudio.csproj]

```

**Comment by jmarrec** [comment]
Running a full build on this branch at https://ci.openstudio.net/blue/organizations/jenkins/openstudio-develop-full/detail/openstudio-develop-full/362/pipeline/11

**Comment by jmarrec** [comment]
Ok 364 replay worked on windows as well: https://ci.openstudio.net/blue/organizations/jenkins/openstudio-develop-full/detail/openstudio-develop-full/364/pipeline/

Testing the windows installer to see if the OpenStudio.dll is in there

**Comment by jmarrec** [comment]
Merging right away, tested it works, and this is going to fix develop nightly builds which is important!
