### PR TITLE
Use conan swig_installer 4.0

### LINKED ISSUE #3607: Update to SWIG 4 on develop3

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #3607

Note that I had to adjust the add_custom_command to pass the SWIG_LIB env variable, since the exe given by conan has swiglib = the one on the build box (CI) used to build it

It worked fine on Ubuntu 18.04, and I was able to use the resulting bindings. I'll let CI produce binaries for other platforms and test.

### CODE REVIEW

**Comment by jmarrec** [comment]
Hum I think for CI to pick up this one correctly we might have to do delete the SWIG_EXECUTABLE from the cache, or the find_program won't look for the new one and keep the old entry... (`unset(SWIG_EXECUTABLE)`)

**Comment by jmarrec** [comment]
It works on Linux, but not on mac where it's hitting this error due to Swig with C++17: https://github.com/swig/swig/issues/1538. This fix is included in swig 4.0.1 

```
/Users/jenkins/git/OpenStudioIncremental/develop3/build/src/utilities/ruby_OpenStudioUtilitiesTime_wrap.cxx:2044:10: error: no type named 'unexpected_handler' in namespace 'std'

    std::unexpected_handler old
```

same on windows
```
D:\jenkins\openstudio\develop3\build\src\utilities\ruby_OpenStudioUtilitiesIdf_wrap.cxx(2045): error C2039: 'unexpected_handler': is not a member of 'std' [D:\jenkins\openstudio\develop3\build\src\utilities\ruby_OpenStudioUtilitiesIdf.vcxproj]

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\map(20): note: see declaration of 'std'

D:\jenkins\openstudio\develop3\build\src\utilities\ruby_OpenStudioUtilitiesIdf_wrap.cxx(2046): error C2039: 'set_unexpected': is not a member of 'std' [D:\jenkins\openstudio\develop3\build\src\utilities\ruby_OpenStudioUtilitiesIdf.vcxproj]

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\map(20): note: see declaration of 'std'

```


* [x] I put it an inclusion request for bincrafters swig_installer 4.0.1 here: https://github.com/bincrafters/community/issues/978
* [x] I also created a recipe myself https://github.com/bincrafters/conan-swig_installer/pull/1
* [x] I updated this PR to use this modified recipe 4.0.1 to see if that fixes it. Left a TODO to switch back to bincrafters' package once available.

**Comment by jmarrec** [comment]
I'm not sure I understand why mac reports a failure https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-incremental-develop3/detail/PR-3676/3/pipeline/8 ? I see the build succeeded and some tests failed, but the log is weird toward the end (aso I don't see each "step" like on Unix / Windows). @tijcolem thoughts?

**Comment by jmarrec** [comment]
swig_installer 4.0.1 is now available on bincrafters, my PR has been merged.

**Comment by tijcolem** [comment]
I re-ran the CI job since we made a pretty big change to develop3 branch since this was last run. 
https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-incremental-develop3/detail/PR-3676/5/pipeline/8/

All looks good so this is good to go.
