### ISSUE TITLE
`json-schema` gem is broken

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#5546]
### Description

Trying to validate a JSON object against a schema throws an error in recent versions of OpenStudio. Since the gem keeps breaking (see [here](https://github.com/NREL/OpenStudio/issues/4870) and [here](https://github.com/NREL/OpenStudio/issues/5208)), it'd be nice if OpenStudio could add a unit test around this.

### Current Behavior

Here's what I get in OpenStudio 3.9, 3.10, and 3.11-rc1:

```
openstudio -e 'require "stringio"; require "json-schema"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'

terminate called after throwing an instance of 'RubyException'
  what():  NoMethodError: undefined method `validate' for nil:NilClass
Aborted (core dumped)
```

### Expected Behavior

It worked in OpenStudio 3.8:

```
openstudio -e 'require "stringio"; require "json-schema"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'

The property '#/a' of type String did not match the following type: integer
```

### Steps to reproduce

See above.

### Environment

Ubuntu 24.04

### Version of OpenStudio

3.11.0-rc1+dee62bf9dd

**Comment by shorowit** [comment]
I noticed that the gem was update in OpenStudio 3.9 from
`json-schema (2.7.0) ':/ruby/3.2.0/gems/json-schema-2.7.0'`
to
`json-schema (4.3.1) ':/ruby/3.2.0/gems/json-schema-4.3.1'`

So it might be related to that?

@jmarrec @anchapin

**Comment by jmarrec** [comment]
Possibly.  Apparently I did that, but probably just because urbanopt was doing it https://github.com/urbanopt/urbanopt-geojson-gem/commit/42fbf675c05ee960f20e011b6cf8bf97e3957c0d

https://github.com/NREL/OpenStudio-workflow-gem/pull/157/commits/a4664b46fb4ef44da4ce2886a4d7f2fcecdd1c11

**Comment by jmarrec** [comment]
Note that tdb also has it as ~> 4

https://github.com/rd2/tbd/blob/7bcd5a156696117e79552faaa5bcd019c98ca2fe/tbd.gemspec#L33

**Comment by jmarrec** [comment]
that is the commit that made it break probably: https://github.com/voxpupuli/json-schema/commit/57639a1a3c8672c726f697e93a2ac10a8ecbacb7

**test.rb**

```ruby
require "json-schema"
schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }
validator = JSON::Validator.new(schema)
pp validator
```

```shell
ruby test.rb > ruby.txt
openstudio test.rb > cli.txt
```

```diff
--- ruby.txt	2025-12-09 09:43:02.677418902 +0100
+++ cli.txt	2025-12-09 09:42:53.991250934 +0100
@@ -1,20 +1,20 @@
-#<JSON::Validator:0x000071a11a6e94c0
+#<JSON::Validator:0x000075fa4e304bc0
  @base_schema=
-  #<JSON::Schema:0x000071a11a6f1800
+  #<JSON::Schema:0x000075fa4e646a18
    @schema=
     {"type"=>"object",
      "required"=>["a"],
      "properties"=>{"a"=>{"type"=>"integer"}}},
-   @uri=#<Addressable::URI:0xc8 URI:18a1ffbb-4681-5b00-bd15-2c76aee4b28f>,
+   @uri=#<Addressable::URI:0x14dc URI:18a1ffbb-4681-5b00-bd15-2c76aee4b28f>,
    @validator=
-    #<JSON::Schema::Draft6:0x000071a11a9750b8
+    #<JSON::Schema::Draft6:0x000075fa4e67de00
      @attributes=
-      {"type"=>JSON::Schema::TypeV4Attribute,
-       "allOf"=>JSON::Schema::AllOfAttribute,
-       "anyOf"=>JSON::Schema::AnyOfAttribute,
-       "oneOf"=>JSON::Schema::OneOfAttribute,
-       "not"=>JSON::Schema::NotAttribute,
-       "disallow"=>JSON::Schema::DisallowAttribute,
+      {"type"=>nil,
+       "allOf"=>nil,
+       "anyOf"=>nil,
+       "oneOf"=>nil,
+       "not"=>nil,
+       "disallow"=>nil,
        "format"=>JSON::Schema::FormatAttribute,
```

**Notice how the attributes stuff has nil values?**

---

Now if I explicitly require the embedded attributes, it works.

**test2.rb**

```ruby
EmbeddedScripting::fileNames.select{|s| s.start_with?(':/ruby/3.2.0/gems/json-schema-4.3.1/lib/json-schema/attributes') }.each {|x| require x};
require "json-schema"
schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }
validator = JSON::Validator.new(schema)
pp validator
puts JSON::Validator.validate(schema, { "a" => "taco" })
```

**Comment by jmarrec** [comment]
Again getting bit by the embedded filesystem and shenanigans we do.

In regular ruby, 

Dir["json-schema/attributes/**/*.rb"] will return

```
json-schema/attributes/attribute.rb
json-schema/attributes/format/format.rb
```

In the CLI, it seems be treating the "**" as a "*" (non optional), so it only returns stuff in subfolder

```
json-schema/attributes/format/format.rb
```
