### ISSUE TITLE
Freeze conan dependencies and vendor them to our remote

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3940]
Enhancement Request
--------------

While we were doing the transition to 3.x, we were actively bumping dependencies etc, for having it break once in a while was fine.

Lately it's become really annoying to have to fix issues due to new versions of packages being released with the same(https://docs.conan.io/en/latest/reference/commands/misc/copy.html) tag. The switch to conan-center-ndex didn't help either, with breaking changes such as casing for cmake targets etc.

## Possible Implementation

* We could just pin the RREV of the packages we use, but we have no way of guaranteeing that they will stay available. (eg: `conan install cppprestsdk/2.10.14@bincrafters/stable#3c644f424a113bc3988b646413724cda5a90f45c`)

* We could stop passing `UPDATE` to conan_cmake_run (equivalent of `conan install --update`) to look for updated packages, and just pin the openstudio_ruby RREV one to ensure ours is updated as needed. But anyone starting a build with a clean conan cache will suddenly have newer versions, and those would likely break stuff.

So instead I think we should do this:

* Vendor all the dependencies to our NREL conan remote, so that we have no risk of seeing the specific recipe revision disappear
    * [conan download](https://docs.conan.io/en/latest/reference/commands/misc/download.html) and/or [conan copy](https://docs.conan.io/en/latest/reference/commands/misc/copy.html)

* Use Revision IDs where appropriate (*if appropriate*... perhaps it's not), for the conan openstudio_ruby one for eg.

Caveats: the revisions have to be enabled by the client (= the user trying to build). Thought if we vendor everything to our remote, by default it'll just pick the latest, which would be set in stone, so perhaps that's enough.

Relevant documention: https://docs.conan.io/en/latest/versioning/revisions.html

**Comment by damianCaceres** [comment]
Good morning:
I'm not to sure if this is the correct issue to report. Please, excuse my low level of English and code.
In order to compile SDK 3.0.0 in Ubuntu 18.04, I've need to reverse to:
zlib/1.2.11@conan/stable
Thank you very much for your patience.

**Comment by jmarrec** [comment]
@damianCaceres not sure I follow. You mean you had to change this line?

https://github.com/NREL/OpenStudio/blob/17912d4d6be39e999fdd174908189b8a61b2ada5/ConanInstall.cmake#L75

Why? What errors were you getting?

(I built on ubuntu last time yesterday and it was fine)

**Comment by brianlball** [comment]
i built yesterday using this Dockerfile and it was fine
[dockerfile](https://github.com/brianlball/build-openstudio/blob/master/Dockerfile)

**Comment by damianCaceres** [comment]
-DBUILD_PYTHON_BINDINGS=ON
Yes. I've changed the line 75 in the file ConanInstall.cmake
I know  because OpenStudio SDK v3.0.0-pre1 works fine
Thank you very much

**Comment by jmarrec** [comment]
Yeah well, without knowing what error you were actually hitting, I can't explain what difference it would make to change the zlib ref. 
It works fine on my multiple ubuntu machines. 
Make sure you have conan 1.24.0 or above

**Comment by damianCaceres** [comment]
damian@damian-HP:~$ conan --version
Conan version 1.24.1

**Comment by damianCaceres** [comment]
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0/build/src/radiance/python_OpenStudioRadiance_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/build.make:1374: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o' failed
make[2]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:3627: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all' failed
make[1]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....


In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0/build/src/gbxml/python_OpenStudioGBXML_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/build.make:1373: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o' failed
make[2]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:3775: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all' failed
make[1]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all] Error 2

**Comment by damianCaceres** [comment]
I can compile with zlib/1.2.11@conan/stable, but the bindings have problems when they are imported. Now I'm starting to test them.
I'll come back to OpenStudio 2.9.1, which works very well. NO URGENT
Thank you

**Comment by damianCaceres** [comment]
After compile OpenStudio 3.0.0 I have got

/usr/local/OpenStudio-3.0.0/Python/_openstudiomodel.so: undefined symbol: _ZTIN10openstudio9WorkspaceE

I imagine that is due to swig 4 ...

**Comment by damianCaceres** [comment]
> It works fine on my multiple ubuntu machines.

Okey

**Comment by jmarrec** [comment]
Ok now we have some info to understand your problem, which seems to be about the python bindings specifically which I don't think anyone has built in a while.

This definitely doesn't belong in this issue which is just about freezing dependencies. Can you open a new one instead? "Problem building python bindings with 3.x" or something like that

**Comment by damianCaceres** [comment]
Nice.
I will have a new issue soon. Before I want to do new tests.
Please, I will be very grateful if you clean up this thread, Freeze conan dependencies.

**Comment by jmarrec** [comment]
@damianCaceres I have opened a new issue in #3961 and try to move your comments over there: please review.
I assigned the issue to me I'll try to build the python bindings and report back.

**Comment by jmarrec** [comment]
Fixed by #4015 : I upload all dependencies we use to NREL's remote (with binary packages for all platforms / settings we use), which I am placing first in line.

In #4047 I will also pin exactly the recipe revisions
