### ISSUE TITLE
Failed to build Python bindings on Ubuntu with 3.x

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3961]
Issue overview
--------------

reported on #3940 by @damianCaceres

## Current Behavior

When building the python bindings `-DBUILD_PYTHON_BINDINGS=ON`, user hit a build error.

```
damian@damian-HP:~$ conan --version
Conan version 1.24.1
```

```
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0/build/src/radiance/python_OpenStudioRadiance_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/build.make:1374: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o' failed
make[2]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:3627: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all' failed
make[1]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....


In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0/build/src/gbxml/python_OpenStudioGBXML_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/build.make:1373: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o' failed
make[2]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:3775: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all' failed
make[1]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all] Error 2


```

User reported trying to change
https://github.com/NREL/OpenStudio/blob/17912d4d6be39e999fdd174908189b8a61b2ada5/ConanInstall.cmake#L75

to `zlib/1.2.11@conan/stable`: 

> Yes. I've changed the line 75 in the file ConanInstall.cmake
I know because OpenStudio SDK v3.0.0-pre1 works fine
Thank you very much

>I can compile with zlib/1.2.11@conan/stable, but the bindings have problems when they are imported. Now I'm starting to test them.
I'll come back to OpenStudio 2.9.1, which works very well. NO URGENT
Thank you

> After compile OpenStudio 3.0.0 I have got
> ```
> /usr/local/OpenStudio-3.0.0/Python/_openstudiomodel.so: undefined symbol: _ZTIN10openstudio9WorkspaceE
> ```
> I imagine that is due to swig 4 ... (wrong comment)

## Expected Behavior

It should work to build the Python bindings

## Steps to Reproduce

Use Ubuntu 18.04, build with  `-DBUILD_PYTHON_BINDINGS=ON`

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 18.04
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.0, 17912d4d6be39e999fdd174908189b8a61b2ada5

### Context

Trying to build the Python Bindings

**Comment by jmarrec** [comment]
@damianCaceres you seem to be building for python3 right? Officially this isn't supported, but it should work (and given that python2 is End-of-Life (EOL) since january 1, it really should)

please provide the following info from build/CMakeCache.txt:

```
$ cd build/
$ grep "PYTHON" CMakeCache.txt 
```

**Comment by damianCaceres** [comment]
Thank you very much. I'm a little bit delayed, by two reasons:

- learning to do good reports, with clean and consistent systems, ... 
- today, in Spanish, the covid-19 confinement has been relaxed. I go to the street with my very old father.

One or two weeks, please.

"Officially this isn't supported,  ..."
Yes, I know and I think about it frequently. As always in the open code world, no warranty. 

Using intensively google  translator and wordReference.

**Comment by damianCaceres** [comment]
I have installed a new, clean and updated Ubuntu 18.04

```

damian@damian-hp:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

```

cmake

```
damian@damian-hp:~$ cmake --version
cmake version 3.17.2

```

conan

```

damian@damian-hp:~$ conan --version
Conan version 1.24.1

```

gcc

```

damian@damian-hp:~$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

```

**Comment by damianCaceres** [comment]
Over this system I have built WITHOUT PYTHON BINDINGS

```

damian@damian-hp:~/OpenStudio-3.0.0/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/openstudio-3.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/damian/OpenStudio-3.0.0/build
damian@damian-hp:~/OpenStudio-3.0.0/build$ make -j6
[100%] Built target openstudio

```

SUCCESSFUL BUILD

**Comment by damianCaceres** [comment]
Firstly WITH PYTHON2 BINDINGS

```

damian@damian-hp:~/OpenStudio-3.0.0-python2.7/build$ cmake .. -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=/usr/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DCMAKE_INSTALL_PREFIX=/usr/local/openstudio-3.0.0-python2.7
-- Configuring done
-- Generating done
-- Build files have been written to: /home/damian/OpenStudio-3.0.0-python2.7/build
damian@damian-hp:~/OpenStudio-3.0.0-python2.7/build$ make -j6
[ 25%] Built target openstudio_model
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2

```

```

[  8%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateConstruction.cpp.o
In file included from /usr/include/python2.7/Python.h:47:0,
                 from /home/damian/OpenStudio-3.0.0-python2.7/build/src/radiance/python_OpenStudioRadiance_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/build.make:1391: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o' failed
make[2]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:2838: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all' failed
make[1]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateConstructionAirBoundary.cpp.o

```

```

[ 11%] Building CXX object src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o
In file included from /usr/include/python2.7/Python.h:47:0,
                 from /home/damian/OpenStudio-3.0.0-python2.7/build/src/gbxml/python_OpenStudioGBXML_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
[ 11%] Building CXX object src/utilities/CMakeFiles/openstudio_utilities.dir/idf/WorkspaceObjectDiff.cpp.o
[ 11%] Building CXX object src/utilities/CMakeFiles/openstudio_utilities.dir/idf/WorkspaceObjectWatcher.cpp.o
[ 11%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateFanConstantVolume.cpp.o
src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/build.make:1390: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o' failed
make[2]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:2955: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all' failed
make[1]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all] Error 2
[ 11%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateFanOnOff.cpp.o

```

```

damian@damian-hp:~/OpenStudio-3.0.0-python2.7/build$ grep "PYTHON" CMakeCache.txt
BUILD_PYTHON_BINDINGS:BOOL=ON
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7
PYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7
PYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython2.7.so
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND
//ADVANCED property for variable: PYTHON_EXECUTABLE
PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_INCLUDE_DIR
PYTHON_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_LIBRARY
PYTHON_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_LIBRARY_DEBUG
PYTHON_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
damian@damian-hp:~/OpenStudio-3.0.0-python2.7/build$ 

```

**Comment by damianCaceres** [comment]
Secondly WITH PYTHON3 BINDINGS

```
damian@damian-hp:~/OpenStudio-3.0.0-python3.6/build$ cmake .. -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.6m -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DCMAKE_INSTALL_PREFIX=/usr/local/openstudio-3.0.0-python3.6
-- Configuring done
-- Generating done
-- Build files have been written to: /home/damian/OpenStudio-3.0.0-python3.6/build
damian@damian-hp:~/OpenStudio-3.0.0-python3.6/build$ make -j6
[ 25%] Built target openstudio_model
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2

```

```

[ 17%] Building CXX object src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0-python3.6/build/src/radiance/python_OpenStudioRadiance_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
[ 17%] Building CXX object src/model/CMakeFiles/openstudio_model.dir/HotWaterEquipmentDefinition.cpp.o
[ 17%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateRefrigerationCondenserAirCooled.cpp.o
[ 17%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateRefrigerationCondenserCascade.cpp.o
src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/build.make:1391: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o' failed
make[2]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/python_OpenStudioRadiance_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:2838: recipe for target 'src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all' failed
make[1]: *** [src/radiance/CMakeFiles/python_OpenStudioRadiance.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateRefrigerationCondenserEvaporativeCooled.cpp.o

```

```

[ 18%] Building CXX object src/model/CMakeFiles/openstudio_model.dir/OutputTableSummaryReports.cpp.o
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/OpenStudio-3.0.0-python3.6/build/src/gbxml/python_OpenStudioGBXML_wrap.cxx:184:
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
[ 18%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateThermalZone.cpp.o
src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/build.make:1390: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o' failed
make[2]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/python_OpenStudioGBXML_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:2955: recipe for target 'src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all' failed
make[1]: *** [src/gbxml/CMakeFiles/python_OpenStudioGBXML.dir/all] Error 2
[ 18%] Building CXX object src/energyplus/CMakeFiles/openstudio_energyplus.dir/ForwardTranslator/ForwardTranslateThermostatSetpointDualSetpoint.cpp.o

```

```

damian@damian-hp:~/OpenStudio-3.0.0-python3.6/build$ grep "PYTHON" CMakeCache.txt
BUILD_PYTHON_BINDINGS:BOOL=ON
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6m
PYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m
PYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND
//ADVANCED property for variable: PYTHON_EXECUTABLE
PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_INCLUDE_DIR
PYTHON_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_LIBRARY
PYTHON_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_LIBRARY_DEBUG
PYTHON_LIBRARY_DEBUG-ADVANCED:INTERNAL=1

```

**Comment by damianCaceres** [comment]
The next days more information. Now I'm going to the street since we have strict walking times.

**Comment by jmarrec** [comment]
I can reproduce on my Ubuntu machine know why this is throwing.

conan-provided `zlib`'s include directory is added to the call as ` -isystem /home/julien/.conan/data/zlib/1.2.11/_/_/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include`, except it does have a file named `crypt.h` in there. This is supposed to be a zlib header that's only internal to zlib. (cf: https://bugzilla.redhat.com/show_bug.cgi?id=1424609 for eg for a similar bug report)

Python on the other hand, is doing `#include <crypt.h>` which is meant to be the system header at `/usr/lib/crypt.h`, so it's throwing because of that.

`/home/julien/.pyenv/versions/3.8.0/include/python3.8/Python.h`:

```
#ifdef HAVE_CRYPT_H
#if defined(HAVE_CRYPT_R) && !defined(_GNU_SOURCE)
/* Required for glibc to expose the crypt_r() function prototype. */
#  define _GNU_SOURCE
#  define _Py_GNU_SOURCE_FOR_CRYPT
#endif
#include <crypt.h>
#ifdef _Py_GNU_SOURCE_FOR_CRYPT
/* Don't leak the _GNU_SOURCE define to other headers. */
#  undef _GNU_SOURCE
#  undef _Py_GNU_SOURCE_FOR_CRYPT
#endif
#endif
```

I'll figure out a fix for this.

**Comment by jmarrec** [comment]
Actually, I think the best is to patch the conan zlib to not install the crypt.h internal-only header, which I've done in https://github.com/conan-io/conan-center-index/pull/1526. I pushed a new `zlib/1.2.11@nrel/testing` with these changes, rebuilding the python bindings but I expect this fixes it.

**Comment by jmarrec** [comment]
@damianCaceres The build error itself is fixed in PR #3963. 

For the unresolved symbols error, I opened another specific issue at https://github.com/NREL/OpenStudio/issues/3964, please use this one now.
