### PR TITLE
Bump deps

### LINKED ISSUE #5229: Boost 1.79.0 errors using Xcode 15.3: upgrade to 1.84.0+
Issue overview
--------------

## Current Behavior

Every new compiler version out there removes deprecated stuff from C++ STD lib, and this is especially true on Xcode / clang.

We're having to define some macros when building via conan `-c tools.build:cxxflags="['-D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']"` and some more inside our cmake.

https://github.com/NREL/OpenStudio/blob/ba1b94b6542c1f1d4cdcdb775886852b9a82bc4f/CMakeLists.txt#L377-L385

## Steps to Reproduce

Update to xcode 15.3 or 15.4

```
 In file included from ./boost/unordered/detail/implementation.hpp:48:
./boost/unordered/detail/fwd.hpp:53:16: error: no member named 'piecewise_construct' in namespace 'std'; did you mean 'piecewise_construct_t'?
    using std::piecewise_construct;
          ~~~~~^~~~~~~~~~~~~~~~~~~
               piecewise_construct_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__utility/piecewise_construct.h:20:29: note: 'piecewise_construct_t' declared here
struct _LIBCPP_TEMPLATE_VIS piecewise_construct_t { explicit piecewise_construct_t() = default; };
```

https://github.com/openstudiocoalition/OpenStudioApplication/actions/runs/9923938518/job/27414679234#step:17:5403

## Possible Solution

Upgrade to a more recent boost, 1.85.0 right now

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all, but especially mac
 - Version of OpenStudio (if using an intermediate build, include SHA): ba1b94b6542c1f1d4cdcdb775886852b9a82bc4f

### Context

Found after upgrading compiler on an arm mac.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5229

I just upgraded to Tahoe 26.4 and got XCode 26.4, which bumped Apple Clang from 17 to 21 (quite a jump).

**-Wno-enum-constexpr-conversion no longer exists, so we can't build with boost 1.79 even with workarounds anymore**

I therefore bumped all deps quite aggressively, then reverted a few:
* libxml2/libxslt: need some rework to allow newer versions
* cpprestsdk forces us to keep boost at 1.86 (1.90 is latest):
     * #5399 
* I had to fix the conan-center swig/4.4.0 recipe, since it didn't have PCRE built in, and that is NOT fine if you try to build C# bindings. 
    * PR is at https://github.com/conan-io/conan-center-index/pull/29907
    * I vendored the recipe to nrel-v2 already, but it doesn't have prebuilt packages

Assuming CI (after building some packages) is still happy, we would vendor the pinned recipes and packages for all platforms we build, as I have historically done. (I have a helper workflow to do so for github actions machines at https://github.com/jmarrec/conan-recipes/blob/main/.github/workflows/upload_deps.yml, I usually also build some niche os/compiler combos myself, the centos stuff)
 

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
The RemoteBCL_BCLSearchResult is failing, and it is not due to this branch, I think this is a bug introduced while updating the BCL to use NLR instead of NREL. I filed it at 

https://github.com/NatLabRockies/new-bcl/issues/173

**Comment by jmarrec** [comment]
I uploaded bumped deps to the nrel-v2 artifactory from github actions from commit d91c69ea7d114d4f2302c08b481c3ceb8e751183

https://github.com/jmarrec/conan-recipes/actions/runs/25434976827

And redid windows in

https://github.com/jmarrec/conan-recipes/actions/runs/25443826236/job/74642271487


I also had to manually rebuild swig on centos-9 because I was hitting GLIBC / GLIBCXX ABI problems, it seems it was built on Ubuntu-24.04 originally so it wouldn't work on either ubuntu-22.04 nor centos-9. I rebuilt on Centos-9 because it has GLIBC 2.34 while Ubuntu has GLIBC 2.35, so older = better

**Comment by jmarrec** [comment]
- [x] I need to reupload the swig and m4 binaries for ubuntu 22.04 arm64
- [ ] Replay that failed run only

**Comment by jmarrec** [comment]
Windows: https://github.com/NatLabRockies/OpenStudio/actions/runs/25445076680/job/74646824076?pr=5606#step:21:1903

```
QuantityFactory.cpp.obj : error LNK2001: unresolved external symbol "public: __cdecl boost::log::v2s_mt_nt6::attribute_set::~attribute_set(void)" (??1attribute_set@v2s_mt_nt6@log@boost@@QEAA@XZ)
```

I know how to fix this, just waiting for centos to finish before I push

**Comment by jmarrec** [comment]
There's a workflow issue: https://github.com/NatLabRockies/OpenStudio/actions/runs/25445076680/job/74646824192?pr=5606#step:18:8419

```
[...]
The following tests FAILED:
	676 - BCLFixture.RemoteBCL_BCLSearchResult (Failed)

Rerunning failing tests...
Test project /__w/OpenStudio/OpenStudio/build
    Start 676: BCLFixture.RemoteBCLMetaSearchTest
1/1 Test #676: BCLFixture.RemoteBCLMetaSearchTest ...   Passed    2.36 sec
```

It's rerunning the wrong test...

I think the bug is that `--rerun-failed` reads test numbers from `LastTestsFailed.log`, but without the same `-E "$final_exclude"` filter, CTest renumbers the tests — so test #676 in the filtered run maps to a different test in the unfiltered rerun.

Here is a demo:

```bash
(py312)(3.2.2)julien@OS-build-release3$ ctest --show-only | rg RemoteBCL_BCLSearchResult
  Test  #678: BCLFixture.RemoteBCL_BCLSearchResult
(py312)(3.2.2)julien@OS-build-release3$ ctest -E 'IddFixture' --show-only | rg RemoteBCL_BCLSearchResult
  Test  #640: BCLFixture.RemoteBCL_BCLSearchResult
```

**Comment by jmarrec** [comment]
I still have a windows issue locally when building the CLI (openstudiolib builds fine)

```
[ 20%][1/5] Building CXX object src\cli\CMakeFiles\openstudio.dir\UpdateCommand.cpp.obj
FAILED: [code=2] src/cli/CMakeFiles/openstudio.dir/UpdateCommand.cpp.obj
C:\ProgramData\chocolatey\bin\ccache.exe C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1444~1.352\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_STACKTRACE_USE_NOOP -DBOOST_STACKTRACE_USE_WINDBG -DBOOST_STACKTRACE_USE_WINDBG_CACHED -DBOOST_USE_WINAPI_VERSION=BOOST_WINAPI_VERSION_WIN8 -DBOOST_WINAPI_DEFINE_VERSION_MACROS -DLIBXML_STATIC -DNOMINMAX -DSHARED_OS_LIBS -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_NO_ASYNCRTIMP -D_NO_PPLXIMP -D_SCL_SECURE_NO_WARNINGS -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -D_SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS -D_SILENCE_FPOS_SEEKPOS_DEPRECATION_WARNING -D_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING -IC:\src\OpenStudio\src -IC:\src\OpenStudio\build-release\src -IC:\src\OpenStudio\build-release -external:IC:\Users\julien\.conan2\p\boost1a2ba2da7aeff\p\include -external:IC:\Users\julien\.conan2\p\bzip25b22578e1ff91\p\include -external:IC:\Users\julien\.conan2\p\zlibfaa27933c9bf2\p\include -external:IC:\Users\julien\.conan2\p\jsonc2e3e5708c40ce\p\include -external:IC:\Users\julien\.conan2\p\cppre27263a705711a\p\include -external:IC:\Users\julien\.conan2\p\opens4aa66747237c6\p\include -external:IC:\Users\julien\.conan2\p\websof2226ef4bf37c\p\include -external:IC:\Users\julien\.conan2\p\pugix1b8594e434fc0\p\include -external:IC:\Users\julien\.conan2\p\libxm22602ceb043b2\p\include -external:IC:\Users\julien\.conan2\p\libxm22602ceb043b2\p\include\libxml2 -external:IC:\Users\julien\.conan2\p\libicdc5ba1d80d05b\p\include -external:IC:\Users\julien\.conan2\p\fmt3886f98945047\p\include -external:IC:\Users\julien\.conan2\p\cli11266c95eaa99d1\p\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /W3 /O2 /Ob2 /DNDEBUG -std:c++20 -MD   /wd4503 /wd4251 /wd4275  /wd4267 /WX /utf-8 /showIncludes /Fosrc\cli\CMakeFiles\openstudio.dir\UpdateCommand.cpp.obj /Fdsrc\cli\CMakeFiles\openstudio.dir\ /FS -c C:\src\OpenStudio\src\cli\UpdateCommand.cpp
C:\Users\julien\.conan2\p\boost1a2ba2da7aeff\p\include\boost/regex/v5/w32_regex_traits.hpp(200): error C2061: syntax error: identifier 'LCTYPE'
C:\Users\julien\.conan2\p\boost1a2ba2da7aeff\p\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2737: 'boost::re_detail_500::lctype': constexpr object must be initialized
C:\Users\julien\.conan2\p\boost1a2ba2da7aeff\p\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2146: syntax error: missing ';' before identifier 'locale_idefaultansicodepage'
C:\Users\julien\.conan2\p\boost1a2ba2da7aeff\p\include\boost/regex/v5/w32_regex_traits.hpp(220): error C2039: 'LCMapStringA': is not a member of '`global namespace''
C:\Users\julien\.conan2\p\boost1a2ba2da7aeff\p\include\boost/regex/v5/w32_regex_traits.hpp(220): error C2873: 'LCMapStringA': symbol cannot be used in a using-declaration
```

I think I tracked down the root cause:

```
  CLI/App.hpp → impl/App_inl.hpp → ../Argv.hpp → impl/Argv_inl.hpp → <windef.h>
```

  `windef.h` defines `BASETYPES` but does not include `winnls.h`, so `LCTYPE` is never defined. Then later when `boost::regex's w32_regex_traits.hpp `sees `BASETYPES` defined, it takes the `#else` path and fails on
  `using` lctype = `LCTYPE.` (#else here: https://github.com/boostorg/regex/blob/4cbcd3078e6ae10d05124379623a1bf03fcb9350/include/boost/regex/v5/w32_regex_traits.hpp#L194)

- after the <windef.h> include in Argv_inl.hpp triggers BASETYPES, boost regex needs LCTYPE. I guess we could add #include <winnls.h> in
  DynamicLibraryWindows.hpp after windows.h is included or something

- add it as a compile option in CMakeLists.txt on Windows:
```cmake
  if(WIN32)
    add_compile_options(/FI winnls.h)   # force-include so LCTYPE is always available
  endif()
```

- Or tell boost regex not to use the Windows API at all with -DBOOST_REGEX_NO_W32. That bypasses the entire #ifndef BASETYPES / LCTYPE dance
    - switches boost::regex from the Windows NLS backend (w32_traits) to the standard C++ locale backend (cpp_traits)
    - I don't think it would have a major impact, given we deal with ASCII mostly...

**Comment by jmarrec** [comment]
Everything appears to be building. The 22.04 arm64 is 1) a fluke probably and 2) not a huge concern.

This is blocking a lot of things, so I'm going to merge this as-is. The full-build.yml workflow needs to be completely revamped IMHO anyways, so it's fine if If we're fixing any issues later on develop. The ability to build with an up-to-date mac trumps it by far.
